阪江 feature/sakae/add_orderitmes_controller
yuya-ishikawa-qa/sumayo pull request #28
Opened 2020-08-13 16:48 UTC by miki-mitsuki

お疲れ様です。

注文管理機能(商品追加、数量変更、商品削除、カート内の商品表示)の実装を行いました。

カート内に入れることができる商品の最大数の管理や画像の表示など
一部機能は後日hotfixのブランチを切って実装予定です。

ご確認のほど、よろしくお願いします。

2020-08-13 21:48 UTC, SekiYukihiro commented on app/Http/Controllers/OrderItmesController.php
> +            return redirect()->route('detail',['id' => $id]);
$idが確実に自然数かどうかを判定されていて、
すごいなと思いました。

せっかくでしたら、不正な値の場合にredirectさせるときに
laravelのフラッシュメッセージという技術を使って

「数量が不正な値です」

などのメッセージをViewに表示させてはいかがでしょうか？

2020-08-13 21:51 UTC, SekiYukihiro commented on app/Http/Controllers/OrderItmesController.php
> +        }
ここも上記と同じでフラッシュメッセージが
使えるかと思います。

2020-08-13 21:53 UTC, SekiYukihiro requested changes
とてもよく書けていると思います！

１点だけ、こうした方がより良いかなという点を記述しましたので
ご確認お願い致します。

宜しくお願い致します。

2020-08-13 23:54 UTC, miki-mitsuki commented on app/Http/Controllers/OrderItmesController.php
> +            return redirect()->route('detail',['id' => $id]);
フラッシュメッセージを使用してエラーメッセージを表示させるよう調整しました。
ご確認お願いいたします。

2020-08-14 00:08 UTC, SekiYukihiro commented
変更点、確認させていただきました！
エラー内容がわかりやすくなったと思います☺️

マージさせて頂きますので、宜しくお願いします！

2020-08-14 00:08 UTC, merged