Feature/takahashi/add store holidays setting function
yuya-ishikawa-qa/sumayo pull request #32
Opened 2020-08-17 13:45 UTC by masanori0117

お疲れ様です。
店舗休日の設定機能を実装しました。
ご確認よろしくお願い致します。

2020-08-17 22:41 UTC, SekiYukihiro commented on resources/views/stores/backup/holiday.blade - Copy.php
> +})
Vueコンポーネントっぽいのがありますが、試しで作っている途中という感じでしょうか？

2020-08-17 22:47 UTC, SekiYukihiro commented on app/Calendar/CalendarWeek.php
> +	}
この関数によって、
HTMLのclassを変更して、適用するCSSを変更する意図でしょうか？

でしたら、名前的にgetClassNameですと、
パッとみた時に、PHPのクラス名を取得するという意味に見えますので
getHtmlClassNameなどにした方が良いかなと思いました！

2020-08-17 22:52 UTC, SekiYukihiro requested changes
確認させて頂きました！

各モデルにメソッドを分けて置かれていて、
かつ、コメントアウトの内容も細かく書いて頂いており、
非常に読みやすい可読性が高いコードだと思いました！☺️

かなりハイレベルだと思います！！

何点かだけ、確認・修正頂きたいことがありましたので
見て各コメントを見て頂けますでしょうか？

宜しくお願い致します！

2020-08-18 04:49 UTC, masanori0117 commented on app/Calendar/CalendarWeek.php
> +	}
すみません、こちらカレンダーのレイアウトを変更してから不要になったので、修正・削除したものをプッシュしました。ご確認よろしくお願い致します。

2020-08-18 04:51 UTC, masanori0117 commented on resources/views/stores/backup/holiday.blade - Copy.php
> +})
こちら、backupディレクトリに入れているファイルは、今後時間があったら使う可能性がありそうということで、backupディレクトリとして残しております。最終的にはこのディレクトリはなくなるので、現時点では無視していただけると幸いでございます。

2020-08-18 13:35 UTC, SekiYukihiro approved these changes
OKです！

マージさせて頂きました！
ご確認お願い致します☺️

2020-08-18 13:36 UTC, merged