さかえOne time
yuya-ishikawa-qa/sumayo pull request #35
Opened 2020-08-19 21:55 UTC by miki-mitsuki

お客様の注文機能追加しました。
なお、DBの店舗情報に紐付いた予約可能かどうかのチェック、メール送信機能は未実装です。
ご確認お願いいたします。

2020-08-19 22:34 UTC, SekiYukihiro commented on app/Http/Controllers/BuyController.php
> +                dd($e);
try~catchとトランザクションも貼られていて
素晴らしいと思います！

ただ、エラーをキャッチした場合、こちらdd()でエラー文を表示させるのではなく
「購入処理に失敗しました」などの文言をユーザに表示させる方が
丁寧かなと思います。

2020-08-19 22:35 UTC, SekiYukihiro commented on app/Http/Controllers/BuyController.php
> +                }
すみません、
僕の理解不足かもですが
こちらはどういう意図の処理でしょうか？

2020-08-19 22:43 UTC, SekiYukihiro commented on app/Http/Controllers/BuyController.php
> +        $return = [];
変数の命名に関してですが
$return
だと、中身が少し分かりにくいので、

$available_dates などにした方がより良いかなと思いました！

2020-08-19 22:43 UTC, SekiYukihiro commented on app/Http/Controllers/BuyController.php
> +        $return = [];
こちらも同じく
変数の命名に関してですが
$return
だと、中身が少し分かりにくいので、

$available_dates などにした方がより良いかなと思いました！

2020-08-19 22:46 UTC, SekiYukihiro requested changes
お疲れ様でした！

コードの可読性も高く、読みやすいと思います☺️

いくつか修正のご提案と
確認事項がありますので、ご確認頂ければと思います！

お手数ですが、宜しくお願い致します。

2020-08-19 23:23 UTC, miki-mitsuki commented on app/Http/Controllers/BuyController.php
> +                dd($e);
デバックコードがそのままになっていました。
削除しましたので、確認お願いいたします。

2020-08-19 23:26 UTC, miki-mitsuki commented on app/Http/Controllers/BuyController.php
> +                }
直前の58行目に問題があり、複数レコードを取得する書き方になっていたため、該当の部分の処理が必要でした。
調整を行いましたのでご確認お願いいたします。

2020-08-19 23:27 UTC, miki-mitsuki commented on app/Http/Controllers/BuyController.php
> +        $return = [];
ありがとうございます。
調整しました。

2020-08-19 23:27 UTC, miki-mitsuki commented on app/Http/Controllers/BuyController.php
> +        $return = [];
ありがとうございます。
調整しました。

2020-08-19 23:59 UTC, merged

2020-08-20 00:00 UTC, SekiYukihiro commented
オーケーです。

各項目について確認して
問題ないと思いますのでマージしました！
お願い致します！