阪江　Feature/sakae/add enter customer information
yuya-ishikawa-qa/sumayo pull request #43
Opened 2020-08-26 21:50 UTC by miki-mitsuki

注文受付時のチェック項目追加しました。
ご確認の程、お願い致します。

2020-08-27 14:32 UTC, SekiYukihiro commented on app/Http/Controllers/BuyController.php
> +                    throw new \Exception('予約可能時間超過の予約');
例外をthrow されているのは素晴らしいと思うのですが
こちら、Laravelのエラーではなく
通常のエラーメッセージとして表示されますでしょうか？

trow new TimeOverException("予約可能時間超過の予約");

などとした後にcatchして
sessionなどでエラー表示させた方が良いのかなと思いました！

2020-08-27 14:52 UTC, SekiYukihiro requested changes
これだけのコードを考えられたのは素晴らしいです！！

ただ、結構処理が長くなってしまっていますね。

今は実装するのが優先だと思いますので、ゆくゆくで良いのですが
関数化して、共通化できる部分を共通化しましょう！

たとえば、showメソッドとstoreメソッドで同様の処理をしている部分もあると思いますので、
そこを纏めるなど、いろいろやり方はあるかと思います☺️


基本的には問題ないと思いますので、
あとは細かい点で
try ~ catch の点などについて記載しましたのでご確認ください！

宜しくお願い致します。

2020-08-29 03:21 UTC, miki-mitsuki commented on app/Http/Controllers/BuyController.php
> +                    throw new \Exception('予約可能時間超過の予約');
>こちら、Laravelのエラーではなく
>通常のエラーメッセージとして表示されますでしょうか？
この部分がよくわからなかったのですが、Laravelのエラーとは404エラーなどのことでしょうか。
上記の認識で問題ないようでしたら、通常のエラーメッセージとして表示させています。

具体的には、エラーの内容にかかわらずエラーが発生した場合は
resources/views/order_confirm.blade.php
の4〜13行目（if文の中のコード）を表示させています。

そのため、
throw new \Exception('予約可能時間超過の予約');
は個別のエラーメッセージを表示するのために使用しているという認識はなく、あくまでデバックの際に参考にできるものという認識です。

>trow new TimeOverException("予約可能時間超過の予約");
>などとした後にcatchして
>sessionなどでエラー表示させた方が良いのかなと思いました！
267行目を
throw new TimeOverException('定休日の予約');
に変えて処理を実行してみたのですが、
Class 'App\Http\Controllers\TimeOverException' not found
のエラーが返ってきました。

新しくControllerを作りその中で例外処理を投げるということをすれば、エラーが解消するという認識ですが、具体的にどのような内容を記載すればいいのかわかりません。
そのため、上記の手順で問題ない場合、新しく作成するControllerの詳細を教えていただければ助かります。
お手数おかけしますが、よろしくお願いいたします。

2020-08-29 14:07 UTC, SekiYukihiro commented on app/Http/Controllers/BuyController.php
> +                    throw new \Exception('予約可能時間超過の予約');
そうです、４０４エラーなどのことです。

なるほど、細かい処理を辿れていませんでしたが、
デバッグ用の処理で書かれていたのですね！

そうすると、この処理に関して、すでにデバッグが完了しているのであれば
このエラーを投げる部分は、もう消しても大丈夫ということになるかなと思ったのですが、いかがでしょうか？
（本番環境で不要なコードが残っているのも、どうかなと思うので）

もし、しばらくデバッグ用で必要ということであれば、
こちらのコードを残したままマージさせて頂きます。


僕が言っていたのは、エラーメッセージをユーザに表示させる必要がある場合限定の話ですが、
app/Exceptions/直下に、TimeOverException.phpを作って独自の例外を作る様な形です。

当然、TimeOverExceptionを作っておらず、名前空間でこちらのコントローラに記載していない段階で使うと、
上記の様な「見つからない」というエラーが出ると想います。

僕が言っていた様な例外を新規に作るのであれば、下記の記事の様な書き方ですかね。
https://qiita.com/komatzz/items/7a5dd78cf66f2c4d6ad5

2020-08-30 03:18 UTC, miki-mitsuki commented on app/Http/Controllers/BuyController.php
> +                    throw new \Exception('予約可能時間超過の予約');
>なるほど、細かい処理を辿れていませんでしたが、
>デバッグ用の処理で書かれていたのですね！
>
>そうすると、この処理に関して、すでにデバッグが完了しているのであれば
>このエラーを投げる部分は、もう消しても大丈夫ということになるかなと思ったのですが、いかがでしょうか？

throw new \Exception('予約可能時間超過の予約');
の部分でデバッグ用の処理という認識なのは
'予約可能時間超過の予約'
のような引数（文字列）の部分のみです。

throw new \Exception('');
に関してはエラーのタイミングでtryの中の処理を終了し、catchの中の処理を実行させるのに必要なコードという認識です。
そのため、消してしまうと、エラーを返さないといけない場面でエラーを返さず、処理が正常終了されて
しまう可能性があるという認識です。

言葉が足りず申し訳ございません。

>僕が言っていたのは、エラーメッセージをユーザに表示させる必要がある場合限定の話ですが、
>app/Exceptions/直下に、TimeOverException.phpを作って独自の例外を作る様な形です。

ご回答ありがとうございます。
本来であれば個別メッセージを表示した方がいい場面であるという認識ですが、UXの面で悩む部分がありますので、個別メッセージの設定は、関数化ように改めて時間を取れるタイミングで行えればと考えています。

上記の部分以外に問題がないようでしたら、このままコミットしていただけると助かります。
よろしくお願いいたします。

2020-08-30 05:32 UTC, SekiYukihiro commented on app/Http/Controllers/BuyController.php
> +                    throw new \Exception('予約可能時間超過の予約');
OKです！
マージさせて頂きました。
ご確認ください。

そうですね、
おっしゃっている通り、開発者として想定内のエラーでしたら
Laravelの開発者向けのエラーのように¥Exceptionとしてthrowするよりも
個別メッセージを表示させる形の方が良いかとは思いますので
今後の参考に、是非ご検討ください。

宜しくお願い致します！

2020-08-30 05:32 UTC, SekiYukihiro commented
OKです！
マージさせて頂きました。
ご確認ください。

そうですね、
おっしゃっている通り、開発者として想定内のエラーでしたら
Laravelの開発者向けのエラーのように¥Exceptionとしてthrowするよりも
個別メッセージを表示させる形の方が良いかとは思いますので
今後の参考に、是非ご検討ください。

宜しくお願い致します！

2020-08-30 05:32 UTC, merged